// AUTO-GENERATED by VARAKH EXECUTOR
// Run: npx playwright test submit.spec.js
// Requires: LABLAB_SESSION_COOKIE or DEVPOST_SESSION_COOKIE env var

const { test, expect } = require('@playwright/test');
const submission = require('./submission_payload.json');

test('submit project to devpost', async ({ page, context }) => {
  // Inject session cookie if provided
  const cookieEnv = process.env.DEVPOST_SESSION_COOKIE;
  if (cookieEnv) {
    const cookies = JSON.parse(cookieEnv);
    await context.addCookies(cookies);
  }

  if (submission.platform === 'lablab') {
    // Navigate to hackathon page
    await page.goto('https://lablab.ai/ai-hackathons');
    await page.waitForLoadState('networkidle');
    
    // Find and click submit/create project button
    const submitBtn = page.locator('text=/submit|create.*project|new.*submission/i').first();
    if (await submitBtn.isVisible()) await submitBtn.click();
    
    // Fill form fields
    await page.fill('input[name*="title"], input[placeholder*="title"], input[placeholder*="name"]', submission.projectName);
    await page.fill('textarea[name*="description"], textarea[placeholder*="description"]', submission.description);
    
    const githubInput = page.locator('input[name*="github"], input[placeholder*="github"], input[placeholder*="repo"]');
    if (await githubInput.isVisible()) await githubInput.fill(submission.repoUrl);
    
    // Submit
    const finalSubmit = page.locator('button[type="submit"], button:text(/submit/i)').first();
    await finalSubmit.click();
    await page.waitForLoadState('networkidle');
    
    // Verify
    await expect(page.locator('text=/submitted|success|thank/i')).toBeVisible({ timeout: 10000 });
    console.log('SUBMITTED TO LABLAB');
  }

  if (submission.platform === 'devpost') {
    await page.goto('https://devpost.com/software/new');
    await page.waitForLoadState('networkidle');
    
    await page.fill('#software_title', submission.projectName);
    await page.fill('#software_tagline', submission.tagline);
    await page.fill('#software_about', submission.description);
    
    const repoInput = page.locator('input[name*="url"], input[placeholder*="URL"]').first();
    if (await repoInput.isVisible()) await repoInput.fill(submission.repoUrl);
    
    const saveBtn = page.locator('button:text(/save|submit/i)').first();
    await saveBtn.click();
    await page.waitForLoadState('networkidle');
    
    await expect(page.url()).toContain('/software/');
    console.log('SUBMITTED TO DEVPOST');
  }
});
